# Auto generated by web.apps.config module

WXMP_TOKEN='laonabuzhai'
WXMP_APP_ID='wxadf692dbf276c755'
WXMP_APP_KEY='d5d70f3c91578b545de3392c8c758dad '
WXMP_ENCODING_AES_KEY='Y81yOIit1k5GZS9Vhx5L1JCOVaQJc9uXnhvaDVKGq4k'
WXMP_MSG_ENCRYPT_METHOD='clear'
